[package]
name = "bevy_quadruped_neural_control"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stillonearth/bevy_quadruped_neural_control"

[dependencies]
bevy = "0.9.1"
bevy_rl = "0.9.5"
bevy_mujoco = { version = "0.0.2" }
bevy-inspector-egui = { version = "0.15.0" }
bevy_flycam = { version = "0.9.0" }
rand = "0.8.5"
serde = "1.0.89"
serde_derive = "1.0.143"
serde_json = "1.0.83"
tract-onnx = "0.18.5"

[profile.dev]
opt-level = 3
